'use client';

import Link from 'next/link';
import { createPortal } from 'react-dom';
import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  ArrowRight, BriefcaseBusiness, Building2, Check, ChevronDown, CircleDot, GitBranch,
  Globe2, Grid2X2, Layers3, Map as MapIcon, MapPin, Network, Plus, Search, Settings2,
  ShieldCheck, Sparkles, UserPlus, Users, X,
} from 'lucide-react';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import { api } from '@/lib/api/client';
import styles from './TeamsListContent.module.css';

type View = 'map' | 'teams' | 'settings';
type NodeType = 'organization' | 'area' | 'region' | 'zone' | 'team' | 'custom';
type Member = { id:string; name:string; email:string; avatarUrl:string|null; jobTitle:string; department:string; workspaceRole:string };
type Structure = { id:string; name:string; description:string|null; is_default:boolean; template:string|null };
type OrgNode = {
  id:string; structure_id:string; parent_id:string|null; name:string; type:NodeType; manager_id:string|null;
  depth:number; position:number; properties:Record<string,any>; memberCount:number; manager:Member|null;
  members:Array<{id:string;user_id:string;role:string;profile:Member|null}>;
  localTeam:{id:string;name:string;slug:string;color:string;status:string;memberCount:number}|null;
};
type LocalTeam = { id:string; name:string; slug:string; description:string|null; color:string; status:string; visibility:string; memberCount:number; hierarchyNodeId:string|null };
type Data = {
  organization:{id:string;name:string;hierarchy_enabled:boolean;hierarchy_config:Record<string,any>};
  structures:Structure[]; activeStructure:Structure|null; nodes:OrgNode[]; members:Member[]; teams:LocalTeam[];
  permissions:{canManage:boolean}; summary:{structures:number;levels:number;nodes:number;members:number;managers:number;teams:number};
};

const META:Record<NodeType,{label:string;description:string}> = {
  organization:{label:'Organización',description:'Raíz de la arquitectura'}, area:{label:'Área',description:'Función o departamento'},
  region:{label:'Región',description:'Cobertura geográfica amplia'}, zone:{label:'Zona',description:'Unidad territorial local'},
  team:{label:'Equipo',description:'Unidad operativa de trabajo'}, custom:{label:'Nivel personalizado',description:'Una división a tu medida'},
};
function NodeIcon({type,size=18}:{type:NodeType;size?:number}){if(type==='organization')return <Building2 size={size}/>;if(type==='region')return <Globe2 size={size}/>;if(type==='zone')return <MapPin size={size}/>;if(type==='team')return <Users size={size}/>;if(type==='area')return <BriefcaseBusiness size={size}/>;return <Grid2X2 size={size}/>}

export function TeamsListContent(){
  const {workspace}=useWorkspace();
  const [view,setView]=useState<View>('map'); const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true);
  const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [structureId,setStructureId]=useState('');
  const [selectedId,setSelectedId]=useState<string|null>(null); const [modal,setModal]=useState<'structure'|'node'|'member'|null>(null);
  const load=useCallback(async(id?:string)=>{setLoading(true);setError('');try{const query=id?`?structureId=${encodeURIComponent(id)}`:'';const{data:body,error}=await api.get<Data>(`/api/workspaces/${workspace.slug}/hierarchy${query}`);if(error||!body)throw new Error(error||'No se pudo cargar la arquitectura');setData(body);setStructureId(body.activeStructure?.id||'');setSelectedId(current=>body.nodes.some((node:OrgNode)=>node.id===current)?current:body.nodes[0]?.id||null)}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo cargar la arquitectura')}finally{setLoading(false)}},[workspace.slug]);
  useEffect(()=>{load()},[load]);
  const selected=data?.nodes.find(node=>node.id===selectedId)||null;
  const children=useMemo(()=>{const map=new Map<string|null,OrgNode[]>();for(const node of data?.nodes||[]){const list=map.get(node.parent_id)||[];list.push(node);map.set(node.parent_id,list)}for(const list of map.values())list.sort((a,b)=>a.position-b.position);return map},[data?.nodes]);
  const teams=useMemo(()=>{const term=search.trim().toLowerCase();return(data?.teams||[]).filter(team=>!term||`${team.name} ${team.description||''}`.toLowerCase().includes(term))},[data?.teams,search]);
  const action=async(body:Record<string,unknown>)=>{const{data:result,error}=await api.post<{structure:{id:string}}>(`/api/workspaces/${workspace.slug}/hierarchy`,body);if(error||!result)throw new Error(error||'No se pudo guardar');return result};
  if(loading&&!data)return <div className={styles.loader}><span/><p>Preparando la arquitectura organizacional…</p></div>;
  return <div className={styles.page}>
    <section className={styles.hero}><div><div className={styles.eyebrow}><Network size={15}/> Centro organizacional</div><h1>Equipos con estructura.</h1><p>Organiza {workspace.name} por áreas, regiones, zonas y equipos desde un mapa conectado con SofLIA.</p></div>{data?.permissions.canManage&&<button className={styles.heroButton} onClick={()=>setModal(data.activeStructure?'node':'structure')}><Plus size={18}/>{data.activeStructure?'Agregar nivel':'Crear estructura'}</button>}<div className={styles.heroRings}/></section>
    {error&&<div className={styles.errorBanner}><CircleDot size={18}/><span>{error}</span><button onClick={()=>load()}>Reintentar</button></div>}
    <section className={styles.stats}><Stat icon={<Layers3/>} label="Estructuras" value={data?.summary.structures||0}/><Stat icon={<GitBranch/>} label="Niveles" value={data?.summary.levels||0}/><Stat icon={<Users/>} label="Personas asignadas" value={data?.summary.members||0}/><Stat icon={<ShieldCheck/>} label="Responsables" value={data?.summary.managers||0}/></section>
    <div className={styles.toolbar}><nav className={styles.tabs}><Tab active={view==='map'} onClick={()=>setView('map')} icon={<MapIcon size={16}/>} label="Mapa organizacional"/><Tab active={view==='teams'} onClick={()=>setView('teams')} icon={<Users size={16}/>} label="Equipos" count={data?.summary.teams}/><Tab active={view==='settings'} onClick={()=>setView('settings')} icon={<Settings2 size={16}/>} label="Configuración"/></nav><span className={`${styles.syncBadge} ${data?.organization.hierarchy_enabled?styles.enabled:''}`}><CircleDot size={13}/> SofLIA {data?.organization.hierarchy_enabled?'activa':'conectada'}</span></div>
    {view==='map'&&<section className={styles.organizer}>
      <aside className={styles.structurePanel}><div className={styles.panelHeading}><span><Network size={18}/></span><div><small>Centro de estructura</small><h2>Arquitectura</h2></div></div><p>Selecciona una estructura y administra sus niveles sin perder el contexto.</p><label className={styles.fieldLabel}>Estructura activa</label><div className={styles.structureList}>{(data?.structures||[]).map(s=><button key={s.id} className={s.id===structureId?styles.structureActive:''} onClick={()=>{setStructureId(s.id);load(s.id)}}><span><Layers3 size={16}/>{s.name}</span>{s.is_default&&<em>Principal</em>}</button>)}</div>{data?.activeStructure&&<div className={styles.activeStructure}><span className={styles.liveDot}/><div><small>Estructura en uso</small><strong>{data.activeStructure.name}</strong></div></div>}<div className={styles.panelActions}>{selected&&<button onClick={()=>setModal('member')}><UserPlus size={16}/> Asignar persona</button>}{data?.permissions.canManage&&<button className={styles.primary} onClick={()=>setModal('structure')}><Plus size={16}/> Nueva estructura</button>}</div></aside>
      <div className={styles.mapPanel}><div className={styles.mapHeader}><div><small>Mapa organizacional</small><h2>{data?.activeStructure?.name||'Sin estructura'}</h2><p>Selecciona un nodo para consultar responsables, personas y equipo vinculado.</p></div><span>{data?.nodes.length||0} unidades</span></div>{!data?.activeStructure?<Empty icon={<Network size={30}/>} title="Diseña la arquitectura de tu organización" text="Empieza con una estructura y añade áreas, regiones, zonas o equipos según tu operación." action={data?.permissions.canManage?<button onClick={()=>setModal('structure')}><Plus size={17}/>Crear primera estructura</button>:null}/>:<div className={styles.mapCanvas}><div className={styles.mapHint}><Sparkles size={14}/> Arquitectura sincronizada con SofLIA</div><div className={styles.tree}>{(children.get(null)||[]).map(node=><Tree key={node.id} node={node} childMap={children} selectedId={selectedId} onSelect={setSelectedId}/>)}</div>{selected&&<Inspector node={selected} canManage={!!data.permissions.canManage} slug={workspace.slug} onAdd={()=>setModal('node')} onAssign={()=>setModal('member')} onClose={()=>setSelectedId(null)}/>}</div>}</div>
    </section>}
    {view==='teams'&&<section className={styles.teamsSection}><div className={styles.sectionHeader}><div><small>Unidades operativas</small><h2>Equipos de {workspace.name}</h2><p>Los equipos vinculados comparten miembros y contexto con SofLIA.</p></div><label className={styles.search}><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar equipos…"/></label></div>{teams.length?<div className={styles.teamGrid}>{teams.map(team=><article className={styles.teamCard} key={team.id}><div className={styles.teamTop}><span className={styles.teamAvatar} style={{'--team-color':team.color} as React.CSSProperties}>{team.name.slice(0,2).toUpperCase()}</span><span className={styles.status}><CircleDot size={12}/>{team.status==='active'?'Activo':team.status}</span></div><h3>{team.name}</h3><p>{team.description||'Equipo listo para colaborar en proyectos y tareas.'}</p><div className={styles.teamMeta}><span><Users size={15}/>{team.memberCount} miembros</span><span><GitBranch size={15}/>{team.hierarchyNodeId?'En jerarquía':'Sin asignar'}</span></div><Link href={`/${workspace.slug}/admin/teams/${team.id}`}>Abrir equipo <ArrowRight size={16}/></Link></article>)}</div>:<Empty icon={<Users size={30}/>} title="Aún no hay equipos" text="Crea un nivel de tipo equipo y Project Hub lo vinculará automáticamente." action={<button onClick={()=>{setView('map');setModal(data?.activeStructure?'node':'structure')}}><Plus size={17}/>Crear equipo</button>}/>}</section>}
    {view==='settings'&&data&&<Settings data={data} onSave={async settings=>{await action(settings);await load(structureId)}}/>}
    {modal==='structure'&&data&&<StructureModal onClose={()=>setModal(null)} onSubmit={async values=>{const result=await action({action:'create_structure',...values,isDefault:data.structures.length===0});setModal(null);await load(result.structure.id)}}/>}
    {modal==='node'&&data?.activeStructure&&<NodeModal structure={data.activeStructure} parent={selected} members={data.members} onClose={()=>setModal(null)} onSubmit={async values=>{await action({action:'create_node',structureId:data.activeStructure!.id,parentId:selected?.id||null,...values});setModal(null);await load(data.activeStructure!.id)}}/>}
    {modal==='member'&&selected&&data&&<MemberModal node={selected} members={data.members.filter(m=>!selected.members.some(a=>a.user_id===m.id))} onClose={()=>setModal(null)} onSubmit={async userId=>{await action({action:'assign_member',nodeId:selected.id,userId});setModal(null);await load(structureId)}}/>}
  </div>
}

function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className={styles.stat}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function Tab({active,onClick,icon,label,count}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;count?:number}){return <button className={active?styles.tabActive:''} onClick={onClick}>{icon}{label}{count!==undefined&&<em>{count}</em>}</button>}
function Tree({node,childMap,selectedId,onSelect}:{node:OrgNode;childMap:Map<string|null,OrgNode[]>;selectedId:string|null;onSelect:(id:string)=>void}){const kids=childMap.get(node.id)||[];return <div className={styles.treeBranch}><button className={`${styles.nodeCard} ${selectedId===node.id?styles.nodeSelected:''}`} onClick={()=>onSelect(node.id)}><span className={styles.nodeIcon}><NodeIcon type={node.type} size={20}/></span><div><small>{META[node.type]?.label||node.type}</small><strong>{node.name}</strong><em>{node.memberCount} {node.memberCount===1?'persona':'personas'}</em></div></button>{kids.length>0&&<div className={styles.treeChildren}>{kids.map(child=><Tree key={child.id} node={child} childMap={childMap} selectedId={selectedId} onSelect={onSelect}/>)}</div>}</div>}
function Inspector({node,canManage,slug,onAdd,onAssign,onClose}:{node:OrgNode;canManage:boolean;slug:string;onAdd:()=>void;onAssign:()=>void;onClose:()=>void}){return <aside className={styles.inspector}><button className={styles.iconButton} onClick={onClose}><X size={17}/></button><small>{META[node.type]?.label||node.type}</small><h3>{node.name}</h3><p>{node.properties.description||'Unidad organizacional conectada con SofLIA.'}</p><dl><div><dt>Responsable</dt><dd>{node.manager?.name||'Sin asignar'}</dd></div><div><dt>Personas</dt><dd>{node.memberCount}</dd></div><div><dt>Ubicación</dt><dd>{[node.properties.city,node.properties.country].filter(Boolean).join(', ')||'Sin definir'}</dd></div></dl><div className={styles.inspectorActions}>{node.localTeam&&<Link href={`/${slug}/admin/teams/${node.localTeam.id}`}>Abrir equipo <ArrowRight size={15}/></Link>}{canManage&&node.type!=='team'&&<button onClick={onAdd}><Plus size={15}/>Subnivel</button>}{canManage&&<button onClick={onAssign}><UserPlus size={15}/>Persona</button>}</div></aside>}

function Settings({data,onSave}:{data:Data;onSave:(value:Record<string,unknown>)=>Promise<void>}){const config=data.organization.hierarchy_config||{};const[enabled,setEnabled]=useState(!!data.organization.hierarchy_enabled);const[auto,setAuto]=useState(!!config.autoAssignNewUsers);const[required,setRequired]=useState(!!config.requireTeam);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');const save=async()=>{setSaving(true);setMessage('');try{await onSave({action:'update_settings',enabled,hierarchyConfig:{...config,autoAssignNewUsers:auto,requireTeam:required}});setMessage('Configuración guardada')}catch(cause){setMessage(cause instanceof Error?cause.message:'No se pudo guardar')}setSaving(false)};return <section className={styles.settingsPanel}><div className={styles.sectionHeader}><div><small>Gobernanza organizacional</small><h2>Configuración de jerarquía</h2><p>Controla cómo se asignan personas y qué alcance tiene cada rol.</p></div></div><div className={styles.settingsGrid}><div className={styles.settingsCard}><Setting icon={<Network/>} title="Jerarquía activa" text="Segmenta proyectos, analítica y permisos." value={enabled} set={setEnabled}/><Setting icon={<UserPlus/>} title="Asignación automática" text="Coloca nuevos usuarios en la unidad predeterminada." value={auto} set={setAuto}/><Setting icon={<Users/>} title="Equipo obligatorio" text="Solicita una unidad antes de activar a una persona." value={required} set={setRequired}/>{data.permissions.canManage&&<div className={styles.saveRow}>{message&&<span>{message}</span>}<button onClick={save} disabled={saving}><Check size={16}/>{saving?'Guardando…':'Guardar configuración'}</button></div>}</div><div className={styles.rolesCard}><small>Alcance por rol</small><h3>Permisos heredados</h3>{[['Propietario','Toda la organización'],['Administrador','Estructuras asignadas'],['Responsable regional','Región y niveles inferiores'],['Líder de equipo','Su equipo y miembros'],['Miembro','Su propia unidad']].map(([role,scope])=><div key={role}><span><ShieldCheck size={15}/>{role}</span><em>{scope}</em></div>)}</div></div></section>}
function Setting({icon,title,text,value,set}:{icon:React.ReactNode;title:string;text:string;value:boolean;set:(v:boolean)=>void}){return <div className={styles.settingRow}><span>{icon}<div><strong>{title}</strong><p>{text}</p></div></span><button className={`${styles.toggle} ${value?styles.toggleOn:''}`} onClick={()=>set(!value)}><span/></button></div>}

function Modal({title,eyebrow,onClose,children}:{title:string;eyebrow:string;onClose:()=>void;children:React.ReactNode}){if(typeof document==='undefined')return null;return createPortal(<div className={styles.modalLayer}><button className={styles.backdrop} onClick={onClose}/><div className={styles.modal}><header><div><small>{eyebrow}</small><h2>{title}</h2></div><button onClick={onClose}><X size={19}/></button></header>{children}</div></div>,document.body)}
function StructureModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(v:{name:string;description:string})=>Promise<void>}){const[name,setName]=useState('');const[description,setDescription]=useState('');const[saving,setSaving]=useState(false);const[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await onSubmit({name,description})}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo crear');setSaving(false)}};return <Modal title="Nueva estructura" eyebrow="Arquitectura organizacional" onClose={onClose}><form onSubmit={submit} className={styles.modalForm}><div className={styles.modalIntro}><span><Network size={22}/></span><div><strong>Un nuevo mapa para tu organización</strong><p>Después podrás añadir áreas, regiones, zonas y equipos.</p></div></div>{error&&<p className={styles.formError}>{error}</p>}<label>Nombre de la estructura<input required autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Estructura comercial 2026"/></label><label>Descripción<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe el alcance…"/></label><footer><button type="button" onClick={onClose}>Cancelar</button><button className={styles.submitButton} disabled={saving}><Plus size={16}/>{saving?'Creando…':'Crear estructura'}</button></footer></form></Modal>}
function NodeModal({structure,parent,members,onClose,onSubmit}:{structure:Structure;parent:OrgNode|null;members:Member[];onClose:()=>void;onSubmit:(v:Record<string,unknown>)=>Promise<void>}){
  const[name,setName]=useState(''); const[description,setDescription]=useState(''); const[type,setType]=useState<NodeType>('team');
  const[managerId,setManager]=useState(''); const[managerOpen,setManagerOpen]=useState(false);
  const[location,setLocation]=useState({city:'',state:'',country:''}); const[saving,setSaving]=useState(false); const[error,setError]=useState('');
  const selectedManager=members.find(member=>member.id===managerId);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await onSubmit({name,description,type,managerId:managerId||null,...location})}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo crear');setSaving(false)}};
  return <Modal title="Agregar nivel" eyebrow={parent?`Dentro de ${parent.name}`:structure.name} onClose={onClose}>
    <form onSubmit={submit} className={styles.modalForm}>
      {error&&<p className={styles.formError}>{error}</p>}
      <label>Nombre<input required autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Región Centro"/></label>
      <div><span className={styles.fieldLabel}>Tipo de nivel</span><div className={styles.typeGrid}>{(['area','region','zone','team','custom'] as NodeType[]).map(option=><button type="button" key={option} className={type===option?styles.typeSelected:''} onClick={()=>setType(option)}><NodeIcon type={option}/><span><strong>{META[option].label}</strong><small>{META[option].description}</small></span>{type===option&&<Check size={15}/>}</button>)}</div></div>
      <label>Descripción<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Propósito y responsabilidades…"/></label>
      <div className={styles.managerField}><span className={styles.fieldLabel}>Responsable</span><button type="button" className={styles.managerTrigger} onClick={()=>setManagerOpen(open=>!open)}><span>{selectedManager?.name||'Sin responsable por ahora'}<small>{selectedManager?.jobTitle||selectedManager?.workspaceRole||'Podrás asignarlo después'}</small></span><ChevronDown size={15}/></button>{managerOpen&&<div className={styles.managerMenu}><button type="button" onClick={()=>{setManager('');setManagerOpen(false)}} className={!managerId?styles.managerSelected:''}>Sin responsable por ahora{!managerId&&<Check size={15}/>}</button>{members.map(member=><button type="button" key={member.id} onClick={()=>{setManager(member.id);setManagerOpen(false)}} className={managerId===member.id?styles.managerSelected:''}><span>{member.name}<small>{member.jobTitle||member.department||member.email}</small></span>{managerId===member.id&&<Check size={15}/>}</button>)}</div>}</div>
      <div className={styles.formColumns}><label>Ciudad<input value={location.city} onChange={e=>setLocation(c=>({...c,city:e.target.value}))}/></label><label>Estado / región<input value={location.state} onChange={e=>setLocation(c=>({...c,state:e.target.value}))}/></label><label>País<input value={location.country} onChange={e=>setLocation(c=>({...c,country:e.target.value}))}/></label></div>
      <footer><button type="button" onClick={onClose}>Cancelar</button><button className={styles.submitButton} disabled={saving}><Plus size={16}/>{saving?'Creando…':type==='team'?'Crear y vincular equipo':'Agregar nivel'}</button></footer>
    </form>
  </Modal>
}
function MemberModal({node,members,onClose,onSubmit}:{node:OrgNode;members:Member[];onClose:()=>void;onSubmit:(id:string)=>Promise<void>}){const[selected,setSelected]=useState('');const[search,setSearch]=useState('');const[saving,setSaving]=useState(false);const[error,setError]=useState('');const filtered=members.filter(m=>`${m.name} ${m.email}`.toLowerCase().includes(search.toLowerCase()));const submit=async()=>{if(!selected)return;setSaving(true);setError('');try{await onSubmit(selected)}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo asignar');setSaving(false)}};return <Modal title="Asignar persona" eyebrow={node.name} onClose={onClose}><div className={styles.memberModal}>{error&&<p className={styles.formError}>{error}</p>}<label className={styles.search}><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre o correo…"/></label><div className={styles.memberList}>{filtered.map(member=><button key={member.id} className={selected===member.id?styles.memberSelected:''} onClick={()=>setSelected(member.id)}><span className={styles.personAvatar}>{member.avatarUrl?<img src={member.avatarUrl} alt=""/>:member.name.slice(0,2).toUpperCase()}</span><span><strong>{member.name}</strong><small>{member.jobTitle||member.department||member.email}</small></span>{selected===member.id&&<Check size={17}/>}</button>)}{!filtered.length&&<p>No hay personas disponibles.</p>}</div><footer><button onClick={onClose}>Cancelar</button><button className={styles.submitButton} disabled={!selected||saving} onClick={submit}><UserPlus size={16}/>{saving?'Asignando…':'Asignar a este nivel'}</button></footer></div></Modal>}
function Empty({icon,title,text,action}:{icon:React.ReactNode;title:string;text:string;action:React.ReactNode}){return <div className={styles.empty}><span>{icon}</span><h3>{title}</h3><p>{text}</p>{action}</div>}
