'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState, type CSSProperties, type FormEvent } from 'react';
import { Archive, ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, Edit3, Globe2, Lock, Plus, Search, Trash2, Users, X } from 'lucide-react';
import { useAuthStore } from '@/core/stores/authStore';
import { api } from '@/lib/api/client';
import { CollectionToolbar, EmptyState, LoadingState, MetricStrip, PageHero, ProductPage, ProductSurface, ToolbarGroup, productControlClass, productInputClass, productInputIconClass, productInputWrapClass, productPrimaryControlClass, type ProductMetric } from '@/components/product';
import styles from './AdminDirectory.module.css';

type Team = { id: string; name: string; slug: string; description: string | null; avatarUrl: string | null; color: string; status: 'active' | 'archived' | 'suspended'; visibility: 'public' | 'private' | 'internal'; maxMembers: number; owner: { id: string; name: string; email: string; avatarUrl: string | null } | null; memberCount: number; createdAt: string };
type TeamForm = { name: string; description: string; color: string; visibility: Team['visibility']; status: Team['status'] };
const emptyForm: TeamForm = { name: '', description: '', color: '#00D4B3', visibility: 'private', status: 'active' };

export function AdminTeamsDirectory() {
  const [teams, setTeams] = useState<Team[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0);
  const [editing, setEditing] = useState<Team | null | undefined>(undefined);
  const currentUserId = useAuthStore((state) => state.user?.id);
  const load = useCallback(async () => { setLoading(true); setError(''); const params = new URLSearchParams({ page: String(page), limit: '10' }); if (search.trim()) params.set('search', search.trim()); const response = await api.get<{ teams?: Team[]; pagination?: { total?: number } }>(`/api/admin/teams?${params}`); if (response.error) setError(response.error); else { setTeams(response.data?.teams || []); setTotal(response.data?.pagination?.total || 0); } setLoading(false); }, [page, search]);
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [load]);
  const metrics = useMemo<ProductMetric[]>(() => [
    { label: 'Equipos', value: total, icon: Users }, { label: 'Activos en esta vista', value: teams.filter((team) => team.status === 'active').length, icon: CheckCircle2, tone: 'success' },
    { label: 'Miembros', value: teams.reduce((sum, team) => sum + team.memberCount, 0), icon: Users, tone: 'info' }, { label: 'Archivados', value: teams.filter((team) => team.status === 'archived').length, icon: Archive },
  ], [teams, total]);
  const remove = async (team: Team) => { if (!window.confirm(`¿Eliminar el equipo ${team.name}? Esta acción no se puede deshacer.`)) return; await api.delete(`/api/admin/teams/${team.id}`); await load(); };
  return <ProductPage>
    <PageHero eyebrow="Estructura global" title="Directorio de equipos" description="Administra unidades de trabajo, propietarios, visibilidad y capacidad desde un mismo lenguaje visual." icon={Users} actions={<button type="button" className={productPrimaryControlClass} onClick={() => setEditing(null)}><Plus size={16} aria-hidden /> Crear equipo</button>} />
    <MetricStrip metrics={metrics} />
    <CollectionToolbar><ToolbarGroup><label className={productInputWrapClass}><Search className={productInputIconClass} size={16} aria-hidden /><input className={productInputClass} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Buscar por nombre o descripción…" /></label></ToolbarGroup><span className={styles.resultCount}>{total} equipos</span></CollectionToolbar>
    <ProductSurface padded>
      {loading ? <LoadingState label="Consultando equipos…" /> : error ? <EmptyState icon={Users} title="No pudimos cargar los equipos" description={error} action={<button type="button" className={productControlClass} onClick={load}>Reintentar</button>} /> : teams.length ? <div className={styles.teamGrid}>{teams.map((team) => <article key={team.id} className={styles.teamCard} style={{ '--team-color': team.color } as CSSProperties}><header><span className={styles.teamAvatar}>{team.avatarUrl ? <img src={team.avatarUrl} alt="" /> : team.name.slice(0, 2).toUpperCase()}</span><span className={styles.badge} data-tone={team.status}>{team.status === 'active' ? 'Activo' : team.status === 'archived' ? 'Archivado' : 'Suspendido'}</span></header><div className={styles.teamCopy}><span className={styles.teamEyebrow}>{team.visibility === 'public' ? <Globe2 size={12} aria-hidden /> : <Lock size={12} aria-hidden />}{team.visibility === 'public' ? 'Público' : team.visibility === 'internal' ? 'Interno' : 'Privado'}</span><h2>{team.name}</h2><p>{team.description || 'Equipo listo para coordinar proyectos y trabajo operativo.'}</p></div><dl><div><dt>Miembros</dt><dd>{team.memberCount}</dd></div><div><dt>Propietario</dt><dd>{team.owner?.name || 'Sin asignar'}</dd></div></dl><footer><Link href={`/admin/teams/${team.id}`}>Abrir equipo <ArrowRight size={15} aria-hidden /></Link><span><button type="button" onClick={() => setEditing(team)} aria-label={`Editar ${team.name}`}><Edit3 size={15} aria-hidden /></button><button type="button" data-danger onClick={() => remove(team)} aria-label={`Eliminar ${team.name}`}><Trash2 size={15} aria-hidden /></button></span></footer></article>)}</div> : <EmptyState icon={Users} title="No encontramos equipos" description="Prueba con otra búsqueda o crea la primera unidad de trabajo." action={<button type="button" className={productPrimaryControlClass} onClick={() => setEditing(null)}><Plus size={16} aria-hidden /> Crear equipo</button>} />}
      {total > 10 ? <footer className={styles.pagination}><span>Página {page} de {Math.ceil(total / 10)}</span><div><button type="button" onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={page === 1}><ChevronLeft size={16} aria-hidden /></button><button type="button" onClick={() => setPage((value) => value + 1)} disabled={page * 10 >= total}><ChevronRight size={16} aria-hidden /></button></div></footer> : null}
    </ProductSurface>
    {editing !== undefined ? <TeamModal team={editing} currentUserId={currentUserId} onClose={() => setEditing(undefined)} onSaved={async () => { setEditing(undefined); await load(); }} /> : null}
  </ProductPage>;
}

function TeamModal({ team, currentUserId, onClose, onSaved }: { team: Team | null; currentUserId?: string; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<TeamForm>(team ? { name: team.name, description: team.description || '', color: team.color, visibility: team.visibility, status: team.status } : emptyForm);
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const update = (key: keyof TeamForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!team && !currentUserId) { setError('No fue posible identificar al propietario del equipo.'); return; } setSaving(true); setError(''); const body = { ...form, ownerId: currentUserId }; const response = team ? await api.put(`/api/admin/teams/${team.id}`, body) : await api.post('/api/admin/teams', body); if (response.error) { setError(response.error); setSaving(false); return; } onSaved(); };
  return <div className={styles.modalLayer}><button type="button" className={styles.backdrop} aria-label="Cerrar" onClick={onClose} /><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="team-modal-title"><header><div><span>Unidad de trabajo</span><h2 id="team-modal-title">{team ? 'Editar equipo' : 'Crear equipo'}</h2><p>Define identidad, alcance y visibilidad del equipo.</p></div><button type="button" onClick={onClose} aria-label="Cerrar"><X size={17} aria-hidden /></button></header><form onSubmit={submit}><div className={styles.formGrid}>{error ? <p className={styles.formError}>{error}</p> : null}<label className={styles.fullField}><span>Nombre</span><input value={form.name} onChange={(event) => update('name', event.target.value)} required /></label><label className={styles.fullField}><span>Descripción</span><textarea value={form.description} onChange={(event) => update('description', event.target.value)} /></label><label><span>Visibilidad</span><select value={form.visibility} onChange={(event) => update('visibility', event.target.value)}><option value="private">Privado</option><option value="internal">Interno</option><option value="public">Público</option></select></label><label><span>Estado</span><select value={form.status} onChange={(event) => update('status', event.target.value)}><option value="active">Activo</option><option value="archived">Archivado</option><option value="suspended">Suspendido</option></select></label><label className={styles.fullField}><span>Color identificador</span><div className={styles.colorField}><input type="color" value={form.color} onChange={(event) => update('color', event.target.value)} /><input value={form.color} onChange={(event) => update('color', event.target.value)} pattern="#[0-9A-Fa-f]{6}" /></div></label></div><footer><button type="button" className={productControlClass} onClick={onClose}>Cancelar</button><button type="submit" className={productPrimaryControlClass} disabled={saving}>{saving ? 'Guardando…' : team ? 'Guardar cambios' : 'Crear equipo'}</button></footer></form></section></div>;
}
